# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install root dependencies
        run: npm ci

      - name: Install API dependencies
        working-directory: ./api
        run: npm ci

      - name: Build API
        working-directory: ./api
        run: npm run build

      - name: Test API
        working-directory: ./api
        run: npm test

      - name: Install Web dependencies
        working-directory: ./web
        run: npm ci

      - name: Build Web
        working-directory: ./web
        run: npm run build

      - name: Test Web
        working-directory: ./web
        run: npm test

